name: simple-streamlit
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.1.3
      - matplotlib==3.8.2
      - streamlit==1.28.2
      - streamlit-lottie==0.0.5
      - seaborn==0.13.0
      - requests==2.31.0
      - numpy==1.26.2
      - plotly==5.17.0
      - scikit-learn==1.3.2
      - statsmodels==0.14.0
